CREATE DATABASE IF NOT EXISTS paradigm;
GRANT ALL ON paradigm.* TO 'laravel'@'%';

CREATE DATABASE IF NOT EXISTS paradigm_logs;
GRANT ALL ON paradigm_logs.* TO 'laravel'@'%';

CREATE DATABASE IF NOT EXISTS ESS0000001;
GRANT ALL ON ESS0000001.* TO 'laravel'@'%';

CREATE DATABASE IF NOT EXISTS ESS0000002;
GRANT ALL ON ESS0000002.* TO 'laravel'@'%';

CREATE DATABASE IF NOT EXISTS ESS0000003;
GRANT ALL ON ESS0000003.* TO 'laravel'@'%';